### ISSUE TITLE
how to get/set username and password

### ISSUE THREAD

**Issue by Aviral2642** [pablosnt/rekono#157]
I installed using cli 
reckon install 

but when I goto the url its asks for id and password ? what is it and how to I set it ? 
while installing I got an option to set smtp and I left it blank but what is this id pass and how can I set it ?

**Comment by pablosnt** [comment]
The SMTP is the configuration to send emails, you can let it blank (of course, you won't receive emails). The username, password and email is the data required to create the initial admin user, you can set the credentials you want. Then you will use this username and password to login in Rekono.

**Comment by Aviral2642** [comment]
i don't think you understood my question, i am saying that if i have
already installed rekono and not set any id pass since i was skipping
setting up SMTP i might have missed setting up id and password for rekono
also, now what can i do ?? How can i set id and pass it now once i have
installed and missed the initial chance of setting up.

**Comment by Aviral2642** [comment]
Creation first Rekono user
Traceback (most recent call last):
  File "/opt/rekono/rekono/manage.py", line 22, in <module>
    main()
  File "/opt/rekono/rekono/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py",
line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py",
line 395, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 24, in
setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 91,
in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/apps/config.py", line 224, in
create
    import_module(entry)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in
_find_and_load_unlocked
ModuleNotFoundError: No module named 'django_filters'

Creating systemd services for Rekono

Installation completed!

**Comment by pablosnt** [comment]
Okay, I'm sorry. You can configure Rekono, including SMTP server, in the `/opt/rekono/config.yaml` file.

About these exception, how did you get it? Also during the `rekono install` execution?

**Comment by Aviral2642** [comment]
here is the terminal output :-

rekono install
Downloading Rekono source code

Installing Rekono dependencies
[+] PostgreSQL
[+] Redis
[+] Vue
[+] Other packages
[+] Rekono backend dependencies
[+] Rekono frontend dependencies

Configuring Rekono
Don't worry if you can't configure some items, press ENTER
SMTP host:
SMTP port:
SMTP user:
SMTP password:

Traceback (most recent call last):
  File "/opt/rekono/rekono/manage.py", line 22, in <module>
    main()
  File "/opt/rekono/rekono/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py",
line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py",
line 395, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 24, in
setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 91,
in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/apps/config.py", line 224, in
create
    import_module(entry)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in
_find_and_load_unlocked
ModuleNotFoundError: No module named 'django_filters'

Creation first Rekono user
Traceback (most recent call last):
  File "/opt/rekono/rekono/manage.py", line 22, in <module>
    main()
  File "/opt/rekono/rekono/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py",
line 419, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py",
line 395, in execute
    django.setup()
  File "/usr/lib/python3/dist-packages/django/__init__.py", line 24, in
setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3/dist-packages/django/apps/registry.py", line 91,
in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/django/apps/config.py", line 224, in
create
    import_module(entry)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in
_find_and_load_unlocked
ModuleNotFoundError: No module named 'django_filters'

Creating systemd services for Rekono

Installation completed!

Do you want to start Rekono services? [Y/N]


i thought it was because of 'django_filters' module missing so i tried to
install it separately :-

pip install django-filter
Defaulting to user installation because normal site-packages is not
writeable
Requirement already satisfied: django-filter in
./.local/lib/python3.11/site-packages (21.1)
Requirement already satisfied: Django>=2.2 in
./.local/lib/python3.11/site-packages (from django-filter) (3.2.18)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from
Django>=2.2->django-filter) (2022.7)
Requirement already satisfied: asgiref<4,>=3.3.2 in
/usr/lib/python3/dist-packages (from Django>=2.2->django-filter) (3.6.0)
Requirement already satisfied: sqlparse>=0.2.2 in
/usr/lib/python3/dist-packages (from Django>=2.2->django-filter) (0.4.2)

but as you can see this is already satisfied now i don't know what maybe
the problem.

**Comment by pablosnt** [comment]
With what local user are you executing this command? Maybe the PIP dependencies are installed in one local user scope and default user creation in other

**Comment by pablosnt** [comment]
`install` command has been removed from Rekono CLI in the last `2.0.0` version. You can try [Rekono Desktop](https://github.com/pablosnt/rekono#rekono-desktop) instead, which is a standalone Desktop application that can be installed easily using a DEB file.
