### ISSUE TITLE
v1.6.2 docker install fails

### ISSUE THREAD

**Issue by zinwelzl** [pablosnt/rekono#240]
git clone https://github.com/pablosnt/rekono
docker-compose build
or sudo docker-compose build still fail

Collecting pycryptodome==3.11.0 (from -r /code/requirements.txt (line 10))
Downloading pycryptodome-3.11.0.tar.gz (3.8 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 6.0 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting psycopg2==2.9.5 (from -r /code/requirements.txt (line 11))
Downloading psycopg2-2.9.5.tar.gz (384 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.3/384.3 kB 5.7 MB/s eta 0:00:00
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting pyjwt==2.4.0 (from -r /code/requirements.txt (line 12))
Downloading PyJWT-2.4.0-py3-none-any.whl (18 kB)
Collecting python-magic==0.4.24 (from -r /code/requirements.txt (line 13))
Downloading python_magic-0.4.24-py2.py3-none-any.whl (12 kB)
Collecting python-libnmap==0.7.3 (from -r /code/requirements.txt (line 14))
Downloading python-libnmap-0.7.3.tar.gz (39 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting python-telegram-bot==13.7 (from -r /code/requirements.txt (line 15))
Downloading python_telegram_bot-13.7-py3-none-any.whl (490 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 490.1/490.1 kB 5.8 MB/s eta 0:00:00
Collecting pyyaml==6.0.0 (from -r /code/requirements.txt (line 16))
Downloading PyYAML-6.0.tar.gz (124 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 5.6 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [48 lines of output]
running egg_info
writing lib/PyYAML.egg-info/PKG-INFO
writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
writing top-level names to lib/PyYAML.egg-info/top_level.txt
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in
main()
File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
return hook(config_settings)
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=['wheel'])
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
self.run_setup()
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
exec(code, locals())
File "", line 288, in
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/init.py", line 107, in setup
return distutils.core.setup(**attrs)
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
return run_commands(dist)
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
dist.run_commands()
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
self.run_command(cmd)
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
super().run_command(command)
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
cmd_obj.run()
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 314, in run
self.find_sources()
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
mm.run()
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 551, in run
self.add_defaults()
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
sdist.add_defaults(self)
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
super().add_defaults()
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
self._add_defaults_ext()
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
self.filelist.extend(build_ext.get_source_files())
File "", line 204, in get_source_files
File "/tmp/pip-build-env-bkvpmgk6/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 107, in getattr
raise AttributeError(attr)
AttributeError: cython_sources
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
The command '/bin/sh -c pip install -r /code/requirements.txt' returned a non-zero code: 1
ERROR: Service 'backend' failed to build : Build failed

pip -V
pip 23.1.2 from /usr/lib/python3/dist-packages/pip (python 3.11)

ip3 -V
pip 23.1.2 from /usr/lib/python3/dist-packages/pip (python 3.11)

**Comment by pablosnt** [comment]
Thank you @zinwelzl for reporting this critical issue! The problem is a new incompatibility with version `6.0.0` of the `pyyaml` dependency, and it's needed to upgrade to `6.0.1`.  The fix is going to be released today. Thank you again!
